### ISSUE TITLE
fix schema object's required field by making it a list

### ISSUE THREAD

**Issue by Algebra8** [Algebra8/pyopenapi3#76]
While create component schemas, if a schema field is marked as `required=True` it does not propagate to the component object properly.

```
@component.schema
class Pet:

    @component.schema_field(
        required=True, example="Susie",
        min_length=1, max_length=100
    )
    def name(self) -> String:
        """Pet's name"""

    @component.schema_field(required=True, example="cat", min_length=1)
    def animal_type(self) -> String:
        """Kind of animal"""
```

The code above should yield a component that looks something like this:

```
Pet:
    type: object
    required:
      - name
      - animal_type
    properties:
      name:
        type: string
        description: Pet's name
        example: "Susie"
        minLength: 1
        maxLength: 100
      animal_type:
        type: string
        description: Kind of animal
        example: "cat"
        minLength: 1
```

However, due to the fact that the ComponentBuilder clumps all fields together, a list for `required` in the top level component schema will not be generated.

To be clear, as is specified in the [swagger docs for OpenAPI3 pertaining to data types](https://swagger.io/docs/specification/data-models/data-types/#object), `required` is an object-level attribute, not a property attribute. But ComponentBuilder is treating it as a property attribute.

Note, the same may apply to other attributes related to `SchemaObject`, such as `enums`. Therefore, object-level attrs should be isolated and built accordingly.
