### ISSUE TITLE
Allow in-line `object` object for Component

### ISSUE THREAD

**Issue by Algebra8** [Algebra8/pyopenapi3#81]
Consider the following example:

```
definitions:
  Pet:
    type: object
    properties:
      tags:
        type: object
        description: Custom tags
```

`tags` is a property of `Pet`, but has type `object`. `tags` can be described with a separate `ObjectsDTSchema`, but should also be allowed in-line, as is the example above.
