### ISSUE TITLE
Allow Free-Form Objects

### ISSUE THREAD

**Issue by Algebra8** [Algebra8/pyopenapi3#82]
Consider the following example:

```
definitions:
  Pet:
    type: object
    properties:
      tags:
        type: object
        description: Custom tags
```

According to [Open API 3 specs on data types](https://swagger.io/docs/specification/data-models/data-types/#object), "a free-form object (arbitrary property/value pairs) is defined as: `type: object`. This is equivalent to `type: object, additionalProperties: true` and `type: object, additionalProperties: {}`."

Free form objects should be allowed.
